### ISSUE TITLE
Photoslide space

### ISSUE THREAD

**Issue by honda-misaki** [manma-web/new_toppage#1]
![manma_web_ol](https://cloud.githubusercontent.com/assets/6498450/11951667/2d1a005c-a8d6-11e5-82af-f57f58a8948b.png)

headerの写真を6枚くらいスライドさせたいです。
アドバイスいただけると大変助かります。
こちらのサイトの該当箇所をペタッと貼っただけなので汚いですが、お手隙の際にご確認お願いいたします。
http://saisaikenbi.com/

**Comment by ebarakazuhiro** [comment]
headerの家族留学Entryの部分は白文字でいいかなと思いました。
パッと見たときにheaderの右部分が切れてるように見えてしまってるので。

**Comment by honda-misaki** [comment]
ご指摘ありがとうございます。
確かにそうですね…そのようにしてみます！

headerはこのようにする予定です。
![manma_web_ol_4](https://cloud.githubusercontent.com/assets/6498450/11953728/af68f9a0-a8e5-11e5-994d-53f6b2fe35b4.jpg)
